export const FETCH_ALL_BOOKS = 'FETCH_ALL_BOOKS';
export const FETCH_ALL_GENRES = 'FETCH_ALL_GENRES';

export const FETCH_BOOK_BY_GENRE = 'FETCH_BOOK_BY_GENRE';
export const FETCH_BOOK_BY_NAME = 'FETCH_BOOK_BY_NAME';

export const SEARCH_BOOK_BY_GENRE = 'SEARCH_BOOK_BY_GENRE';

export const FETCH_BOOK_BY_GENRE_ID = 'FETCH_BOOK_BY_GENRE_ID';
export const FETCH_BOOK_DETAILS = 'FETCH_BOOK_DETAILS';

export const AJAX_ERROR = 'AJAX_ERROR';